cd /home/pi/PiServerSpringBoot
lcd build/libs
rm PiServerSpringBoot-1.0.old.jar
rename PiServerSpringBoot-1.0.jar PiServerSpringBoot-1.0.old.jar
put PiServerSpringBoot-1.0.jar
chmod 775 PiServerSpringBoot-1.0.jar

cd /home/pi/PiServer
lcd ../..
put configWebApp.json
put runWebApp.sh
chmod 775 runWebApp.sh

cd /home/pi/PiServer/web/scripts
lcd ../web/scripts
mput *.*
chmod 775 *.sh

cd /home/pi/PiServer/web/audio
lcd ../../web/audio
mput *.*

quit

